### PR TITLE
new: integrating frontend with backend

### LINKED ISSUE #2: feat: integrate with frontend
- integrate server with frontend

### PR DESCRIPTION
**Pull request by sidmohanty11**
- added basic UI
- integrated frontend with backend

noticeboard1

closes #2

### CODE REVIEW

**Review by subrat0796 — COMMENTED** [review]
Why are we getting multiple times the same notice ?

**Comment by sidmohanty11** [comment]
> Why are we getting multiple times the same notice ?

if you see here, allNotice is a global variable (array)
```javascript
let allNotice = [];
```
so when the server stays on it keeps pushing onto it

@subrat0796

**Comment by sidmohanty11** [comment]
@subrat0796 we need to handle it, storing all the notice in MongoDB

deleting the existing ones if required

**Comment by subrat0796** [comment]
> @subrat0796 we need to handle it, storing all the notice in MongoDB
> 
> deleting the existing ones if required

Did you check that the data you are getting and the url in the link is same ?

**Comment by sidmohanty11** [comment]
> > @subrat0796 we need to handle it, storing all the notice in MongoDB
> > deleting the existing ones if required
> 
> Did you check that the data you are getting and the url in the link is same ?

yup, got it

**Pull request merged**
